// GENERATED by build-shell.mjs — do not edit.
//
// A static index of the voiceover timelines on disk. It has to be generated
// rather than read at runtime: the composition is bundled for a browser, which
// cannot look in a directory, and Remotion needs the video's duration before it
// renders a single frame.
//
// Committed, because the timelines themselves are: text-to-speech is not
// reproducible, so the audio and its measurements are inputs to a render rather
// than outputs of one.

import type { VoiceTimeline } from "../src/voice";

export const VOICE_TIMELINES: Record<string, VoiceTimeline> = {
};
